export const ERROR_FACILITY_LIST = 'ERROR_FACILITY_LIST';
export const REQUEST_FACILITY_LIST = 'REQUEST_FACILITY_LIST';
export const SUCCESS_FACILITY_LIST = 'SUCCESS_FACILITY_LIST';

export const ERROR_ACTIVITY_LIST = 'ERROR_ACTIVITY_LIST';
export const REQUEST_ACTIVITY_LIST = 'REQUEST_ACTIVITY_LIST';
export const SUCCESS_ACTIVITY_LIST = 'SUCCESS_ACTIVITY_LIST';
